server:
  port: 8086

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/hospital?serverTimezone=Asia/Shanghai&useSSL=false
    username: root
    password: root
  #security配置
  jackson:
    serialization:
      indent_output: true
  redis:
    host: 127.0.0.1
    port: 6379
    jedis:
      pool:
        min-idle: 0
        max-idle: 8
        max-active: 8
        max-wait: -1ms

mybatis:
  type-aliases-package: com.yy.hospital.domain
  configuration:
    map-underscore-to-camel-case: true
  mapper-locations: classpath:mybatis/mapper/*.xml

logging:
  level:
    org.springframework.security: info
    com.yy.hospital.mapper: debug
    com.yy.hospital.util: debug
  file: logs/all.log   # 定义日志文件路径（相对路径）本来是不用写的，但是log4j.properties里面的文件输出有问题

jwt:
  header: Authorization  #请求头部属性名
  secret: mySecret       #在令牌里面加上自己设定的口令
  expiration: 604800    #token失效的时间（秒）
  route:                 #访问路径
      authentication:
        path: /auth
        refresh: /refresh